export const openAiModels = [
  { id: "o1", name: "OpenAI o1" },
  { id: "o1-mini", name: "OpenAI o1 Mini" },
  { id: "o1-preview", name: "OpenAI o1 (Preview)" },
  { id: "o3-mini", name: "OpenAI o3 Mini" },
  { id: "o3", name: "OpenAI o3" },
  { id: "o4-mini", name: "OpenAI o4 Mini" },
  { id: "gpt-4.1", name: "GPT-4.1" },
  { id: "gpt-4.1-mini", name: "GPT-4.1 Mini" },
  { id: "gpt-4.1-nano", name: "GPT-4.1 Nano" },
  { id: "gpt-4o", name: "GPT-4o" },
  { id: "gpt-4o-audio-preview", name: "GPT-4o Audio (Preview)" },
  { id: "gpt-4o-search-preview", name: "GPT-4o Search (Preview)" },
  { id: "gpt-4o-mini-search-preview", name: "GPT-4o Mini Search (Preview)" },
  { id: "gpt-4o-mini", name: "GPT-4o Mini" },
  { id: "gpt-4o-mini-2024-07-18", name: "GPT-4o Mini (2024-07-18)" },
  { id: "gpt-4-turbo", name: "GPT-4 Turbo" },
  { id: "gpt-4-turbo-preview", name: "GPT-4 Turbo (Preview)" },
  { id: "gpt-4", name: "GPT-4" },
  { id: "gpt-4.5-preview", name: "GPT-4.5 (Preview)" },
  { id: "gpt-3.5-turbo-0125", name: "GPT-3.5 Turbo (0125)" },
  { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo" },
  { id: "gpt-3.5-turbo-1106", name: "GPT-3.5 Turbo (1106)" },
  { id: "chatgpt-4o-latest", name: "ChatGPT-4o (Latest)" },
] satisfies { id: string; name: string }[];
