async function fetchOpenRouterModels() {
  const url = "https://openrouter.ai/api/v1/models";
  try {
    const response = await fetch(url);
    if (!response.ok) {
      throw new Error(`HTTP error! status: ${response.status}`);
    }
    const body = await response.json();
    // console.log(JSON.stringify(data, null, 2));
    return body.data;
  } catch (error) {
    console.error("Error fetching OpenRouter models:", error);
    return null;
  }
}

async function saveModelsToFile() {
  const models = await fetchOpenRouterModels();
  const cleanerOutput = models.map((model) => ({
    id: model.id,
    name: model.name,
    description: model.description,
  }));

  if (models) {
    const filePath = "src/lib/llm/openrouter.ts";
    const fileContent = `// DO NOT EDIT: Generated by script, do not edit manually
// Last updated: ${new Date().toISOString()}
export const openRouterModels = ${JSON.stringify(
      cleanerOutput,
      null,
      2
    )} as const;
`;
    try {
      await Bun.write(filePath, fileContent);
      console.log(`Successfully wrote models to ${filePath}`);
    } catch (error) {
      console.error(`Error writing to file ${filePath}:`, error);
    }
  }
}

saveModelsToFile();
